jreleaser/jreleaser.github.io

docs/modules/ROOT/pages/links.adoc

Fix twitter link

---

docs/modules/configuration/pages/release/gitlab.adoc

Relates to https://github.com/jreleaser/jreleaser/pull/168

[gitlab] Added Identifier documentation

---

docs/modules/configuration/pages/packagers/jbang.adoc

JBang is the project name,
jbang is the cli/short name
Jbang is an error :)
Fixes #?

proper jbang casing

---

docs/modules/configuration/pages/announce/discussions.adoc

Fixes https://github.com/jreleaser/jreleaser.github.io/pull/8#issue-666303371?

Note about organization repositories

---

docs/modules/configuration/pages/packagers/scoop.adoc
docs/modules/configuration/partials/platform.adoc

Fix typos / copy-paste errors

---

docs/modules/configuration/pages/release/github.adoc

Fix typo in github.adoc

---

docs/modules/configuration/pages/files.adoc

Missing an 's'

---

docs/modules/configuration/pages/environment.adoc
docs/modules/configuration/pages/name-templates.adoc
docs/modules/configuration/partials/release/changelog.adoc
docs/modules/configuration/partials/release/gradle/common-head.adoc
docs/modules/configuration/partials/release/json/common-head.adoc
docs/modules/configuration/partials/release/maven/common-head.adoc
docs/modules/configuration/partials/release/toml/common-head.adoc
docs/modules/configuration/partials/release/yaml/common-head.adoc

Fixes https://github.com/jreleaser/jreleaser/issues/382
Is it clear what the new configuration does?

Document https://github.com/jreleaser/jreleaser/issues/382

---

docs/modules/configuration/partials/release/maven/changelog.adoc
docs/modules/configuration/partials/release/toml/changelog.adoc
docs/modules/configuration/partials/release/yaml/changelog.adoc

Add missing curly bracket in changelog doc

---

docs/modules/configuration/partials/packagers/maven/template-directory.adoc

Fix xml in maven example.

---

docs/modules/configuration/pages/packagers/homebrew.adoc

Hey @aalmiray, this fixes a small formatting glitch I noticed while reading up on the homebrew stuff.

Formatting fix

---

docs/modules/tools/pages/jreleaser-cli.adoc

Just tried on my Win10 WSL based Ubuntu

doc: `brew` install works on Linux as well

---

docs/modules/configuration/pages/packagers/homebrew.adoc

Fix depencency typo

---

docs/modules/examples/pages/maven/maven-central.adoc

`development` branch seems to be outdated w.r.t `main`.
Fixes #37

Add caution note for sonatype legacy url

---

docs/modules/examples/pages/maven/maven-central.adoc

Fix Maven Central URL property

---

antora-playbook.yml
local-playbook.yml

Point Edit this page to the development branch

---

docs/modules/reference/partials/packagers/token.adoc

#47 Updating information on fine-grained GitHub PATs

---

docs/modules/reference/pages/assemble/jlink.adoc

fix: Use correct closing tag.

---

docs/modules/reference/pages/assemble/jlink.adoc

Sorry, one more… Was too quick on the first time.

fix: Close `additionalModuleNames`.

---

docs/modules/reference/pages/packagers/homebrew.adoc

Relates to PR jreleaser/jreleaser#1269

document jreleaser/jreleaser#1269

---

docs/modules/ROOT/pages/integrations.adoc
docs/modules/reference/nav.adoc
docs/modules/reference/pages/announce/bluesky.adoc
docs/modules/reference/pages/name-templates.adoc

Fixes https://github.com/jreleaser/jreleaser/pull/1380

feat: add bluesky documentation

---

docs/modules/reference/partials/deploy/maven/gradle/common-head.adoc
docs/modules/reference/partials/deploy/maven/json/common-head.adoc
docs/modules/reference/partials/deploy/maven/maven/common-head.adoc
docs/modules/reference/partials/deploy/maven/toml/common-head.adoc
docs/modules/reference/partials/deploy/maven/yaml/common-head.adoc

Document the new failOnWarning and failOnError configuration for pomchecker as introduced in jreleaser/jreleaser#1402

Document jreleaser/jreleaser#1402

---

docs/modules/continuous-integration/nav.adoc
docs/modules/continuous-integration/pages/jetbrains-space.adoc

In correspondance with the following discussion/ idea https://github.com/jreleaser/jreleaser/discussions/1426

Add Jetbrains Space documentation with example

---

docs/modules/concepts/pages/distributions/flat-binary.adoc

... and it's not even Hacktoberfest yet ;-)

docs: Fix typo

---

docs/modules/reference/pages/name-templates.adoc

Relates to https://github.com/jreleaser/jreleaser/pull/1497
Fixes #?

Add missing template variables

---

docs/modules/examples/pages/maven/maven-central.adoc

I was copying and using it as it is and encountered an error.. 
I think this is a typo.
I ran into an error while copying the same.
secrete Key -> secret Key

 Fix typo in JReleaser with gradle

---

docs/modules/ROOT/pages/schema.adoc
docs/modules/tools/pages/jreleaser-ant.adoc
docs/modules/tools/pages/jreleaser-cli.adoc
docs/modules/tools/pages/jreleaser-gradle.adoc
docs/modules/tools/pages/jreleaser-maven.adoc

Anchors were wrong (cf. aim42/htmlSanityCheck#342)

Fix wrong anchor usage (cf. aim42/htmlSanityCheck#342).

---

docs/modules/reference/pages/project.adoc

Fixes jreleaser/jreleaser#1728
Documents changes from jreleaser/jreleaser#1729

Document jreleaser/jreleaser#1729

---

docs/modules/reference/pages/announce/bluesky.adoc

Fixes [#1766](https://github.com/jreleaser/jreleaser/issues/1766)

Document https://github.com/jreleaser/jreleaser/issues/1766

---

docs/modules/extensions/pages/authoring-extensions.adoc
docs/modules/reference/pages/extensions.adoc

Documents jbang extensions, see https://github.com/jreleaser/jreleaser/issues/1952

Document https://github.com/jreleaser/jreleaser/issues/1952
